### ISSUE TITLE
Бесконечная загрузка артбордов

### ISSUE THREAD

**Issue by lozianko** [ruslanlatypov/Mockup-Plugin-for-Sketch#1]
Бесконечная загрузка в плагине если в документе присутствует символ из какой-то внешней библиотеки. Если символы есть внутри документа, то они тоже воспринимаются как артборды.
Было бы удобно их исключить или дать такую возможность пользователю.

**Comment by vladbers** [comment]
Спасибо! Очень важное замечание, в ближайшее время поправим этот баг
