### ISSUE TITLE
Plugin has problems applying artboards correctly since Sketch 83

### ISSUE THREAD

**Issue by christophevouillamoz** [ruslanlatypov/Mockup-Plugin-for-Sketch#3]
Somehow Sketch changed something that seams to have negative effect on how the plugin is working. Applying artboards on the rectangles not give me the expected result. I have this problem also in the original Sketch resources. I also tried to turn or mirror the artboard but could not have it the right way.

![Bildschirmfoto 2022-02-14 um 15 59 51](https://user-images.githubusercontent.com/1191035/153888909-606d8f61-6783-46e1-91ab-3eabc6b7e44d.png)

**Comment by ruslanlatypov** [comment]
> Somehow Sketch changed something that seams to have negative effect on how the plugin is working. Applying artboards on the rectangles not give me the expected result. I have this problem also in the original Sketch resources. I also tried to turn or mirror the artboard but could not have it the right way.

Hi Christophe, thank you.
Please use another link
(Depends on your Safari version)

if you have Safari v.14 and below
https://github.com/ruslanlatypov/Mockup-Plugin-for-Sketch/releases/download/v2.0.4/mockup.sketchplugin.zip
If you have Safari v.15 and above
https://github.com/ruslanlatypov/Mockup-Plugin-for-Sketch/releases/download/v2.0.5.1/mockup2.0.5.1.sketchplugin.zip

**Comment by christophevouillamoz** [comment]
Thanks a lot for this fast reply. Obviously this was not an Sketch or Plugin issue but the Update of my Mac OS ;) Problem solved!
